### ISSUE TITLE
Pre-selected frames - page clone

### ISSUE THREAD

**Issue by moriatea** [stevahnes/figma-plugins#10]
It would help a lot if the frames that are in the page that are not hidden are selected when the list of frames is shown

**Comment by stevahnes** [comment]
Hi @moriatea this is already implemented.

The condition is as follows:
1. If you launch the plugin with one/more frames selected, then only that selected frame is checked.
2. However, if you launch the plugin without pre-selecting any frames, then all frames are checked by default.

This design is such that you can select more than one frame using the left pane of Figma (where all your frames are listed) and then launch the app. When this happens, whatever frames you've pre-selected will be checked by PageClone.

Hope this clarifies!
