### ISSUE TITLE
[Feature Request] Detach styles

### ISSUE THREAD

**Issue by cheesebuhrger** [stevahnes/figma-plugins#8]
Amazing work on this plugin!

I would love to have the option to detach styles (i.e. colors, typography, effects). It's a good plugin to use to keep snapshots of work as you iterate, but have to detach styles manually.

**Comment by stevahnes** [comment]
Hello! Thank you for your kind words :) Glad you enjoyed using the plugin!
May I know which plugin you are exactly referring to? As you can see in the repo there are 4 plugins :)
I can start seeing the feasibility once you let me know!

**Comment by cheesebuhrger** [comment]
Ah, talking about PageClone specifically. Sorry 'bout that!

**Comment by stevahnes** [comment]
No problem! Let me see what I can do :) Will try to code it out as soon as possible. Again, thanks for using my plugin :)

**Comment by stevahnes** [comment]
Hi @cheesebuhrger, while doing a fix for another issue, I should've made it such that Styles are now detached. Can you help test the latest 2.2.5 version and see if this is done? Thanks!

**Comment by stevahnes** [comment]
Closing this as feature is already implemented in 2.2.5 onwards, and no response from logger :)
